import { Link } from "react-router-dom";
import { useMutation, useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api-client";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/feedback/empty-state";
import { LoadingState } from "@/components/feedback/loading-state";
import { ErrorState } from "@/components/feedback/error-state";

export function BookingsPage() { const query = useQuery({ queryKey: ["bookings"], queryFn: api.bookings }); if (query.isLoading) return <LoadingState />; if (query.isError) return <ErrorState message="Booking belum dapat dimuat." onRetry={() => void query.refetch()} />; if (!query.data) return <ErrorState message="Data booking kosong." onRetry={() => void query.refetch()} />; return <div className="space-y-6 pt-3"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-orange-600">Branch booking</p><h1 className="mt-2 font-display text-3xl font-bold">Booking aktif</h1></div>{query.data.length === 0 ? <EmptyState title="Belum ada booking aktif" detail="Cari cabang dan pilih jadwal untuk membuat booking." /> : <div className="grid gap-4">{query.data.map((booking) => <BookingCard key={booking.booking_code} bookingCode={booking.booking_code} status={booking.status} branch={booking.branch_name ?? booking.branch_id} schedule={`${booking.appointment_date} · ${booking.start_time} - ${booking.end_time}`} />)}</div>}</div>; }
function BookingCard({ bookingCode, status, branch, schedule }: { bookingCode: string; status: string; branch: string; schedule: string }) { const checkIn = useMutation({ mutationFn: () => api.checkIn(bookingCode) }); return <Card className="p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-bold">{branch}</h2><p className="mt-1 text-sm text-slate-600">{schedule}</p><p className="mt-2 text-xs text-slate-500">Ref: {bookingCode}</p></div><Badge tone={status === "CONFIRMED" ? "success" : "warning"}>{status}</Badge></div><div className="mt-5 flex gap-3"><Link to={`/app/bookings/${bookingCode}`}><Button variant="secondary">Detail</Button></Link><Button disabled={checkIn.isPending || ["CANCELLED", "EXPIRED", "COMPLETED"].includes(status)} onClick={() => checkIn.mutate()}>Check-in</Button></div>{checkIn.data && <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">{checkIn.data.message}</p>}</Card>; }
