import { useQuery } from "@tanstack/react-query";
import { useLocation, useParams } from "react-router-dom";
import { api } from "@/lib/api-client";
import { formatCurrency, formatDate } from "@/lib/format";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { LoadingState } from "@/components/feedback/loading-state";
import { ErrorState } from "@/components/feedback/error-state";

export function CreditDetailPage() { const { id = "" } = useParams(); const isStaff = useLocation().pathname.startsWith("/staff/"); const application = useQuery({ queryKey: ["credit-application", isStaff, id], queryFn: () => isStaff ? api.staffCreditApplication(id) : api.creditApplication(id), enabled: Boolean(id) }); const events = useQuery({ queryKey: ["credit-events", isStaff, id], queryFn: () => isStaff ? api.staffCreditApplicationEvents(id) : api.creditApplicationEvents(id), enabled: Boolean(id) }); if (application.isLoading) return <LoadingState />; if (application.isError || !application.data) return <ErrorState message="Pengajuan tidak ditemukan atau tidak dapat diakses." onRetry={() => void application.refetch()} />; return <div className="max-w-3xl space-y-6 pt-3"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-orange-600">Simulated financing</p><h1 className="mt-2 font-display text-3xl font-bold">{application.data.product_category.replaceAll("_", " ")}</h1><p className="mt-2 text-slate-500">{formatCurrency(application.data.requested_amount, application.data.currency)} · dibuat {formatDate(application.data.created_at)}</p></div><Card className="p-6"><div className="flex items-center justify-between"><h2 className="font-bold">Current stage</h2><Badge tone="warning">{application.data.current_stage.replaceAll("_", " ")}</Badge></div><h2 className="mt-7 font-bold">Document checklist</h2><div className="mt-3 divide-y divide-line">{application.data.documents.map((document) => <div key={document.id} className="flex justify-between py-3 text-sm"><span>{document.document_code.replaceAll("_", " ")}</span><span className="font-bold text-slate-500">{document.status}</span></div>)}</div></Card><Card className="p-6"><h2 className="font-bold">Timeline</h2>{events.isError ? <p className="mt-3 text-sm text-slate-500">Timeline belum tersedia.</p> : events.data?.items.length === 0 ? <p className="mt-3 text-sm text-slate-500">Belum ada event.</p> : <div className="mt-3 divide-y divide-line">{events.data?.items.map((event) => <div key={String(event.id)} className="py-3 text-sm"><p className="font-bold">{String(event.event_type).replaceAll("_", " ")}</p><p className="mt-1 text-slate-500">{String(event.customer_note ?? "Progress diperbarui")}</p></div>)}</div>}</Card></div>; }